// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: protocol.proto

#include "protocol.pb.h"
#include "protocol.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace mastodon_blender_view {

static const char* ViewService_method_names[] = {
  "/mastodon_blender_view.ViewService/addMovingSpot",
};

std::unique_ptr< ViewService::Stub> ViewService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ViewService::Stub> stub(new ViewService::Stub(channel, options));
  return stub;
}

ViewService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_addMovingSpot_(ViewService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ViewService::Stub::addMovingSpot(::grpc::ClientContext* context, const ::mastodon_blender_view::AddMovingSpotRequest& request, ::mastodon_blender_view::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::mastodon_blender_view::AddMovingSpotRequest, ::mastodon_blender_view::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_addMovingSpot_, context, request, response);
}

void ViewService::Stub::async::addMovingSpot(::grpc::ClientContext* context, const ::mastodon_blender_view::AddMovingSpotRequest* request, ::mastodon_blender_view::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::mastodon_blender_view::AddMovingSpotRequest, ::mastodon_blender_view::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_addMovingSpot_, context, request, response, std::move(f));
}

void ViewService::Stub::async::addMovingSpot(::grpc::ClientContext* context, const ::mastodon_blender_view::AddMovingSpotRequest* request, ::mastodon_blender_view::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_addMovingSpot_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::mastodon_blender_view::Empty>* ViewService::Stub::PrepareAsyncaddMovingSpotRaw(::grpc::ClientContext* context, const ::mastodon_blender_view::AddMovingSpotRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::mastodon_blender_view::Empty, ::mastodon_blender_view::AddMovingSpotRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_addMovingSpot_, context, request);
}

::grpc::ClientAsyncResponseReader< ::mastodon_blender_view::Empty>* ViewService::Stub::AsyncaddMovingSpotRaw(::grpc::ClientContext* context, const ::mastodon_blender_view::AddMovingSpotRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncaddMovingSpotRaw(context, request, cq);
  result->StartCall();
  return result;
}

ViewService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ViewService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ViewService::Service, ::mastodon_blender_view::AddMovingSpotRequest, ::mastodon_blender_view::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ViewService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::mastodon_blender_view::AddMovingSpotRequest* req,
             ::mastodon_blender_view::Empty* resp) {
               return service->addMovingSpot(ctx, req, resp);
             }, this)));
}

ViewService::Service::~Service() {
}

::grpc::Status ViewService::Service::addMovingSpot(::grpc::ServerContext* context, const ::mastodon_blender_view::AddMovingSpotRequest* request, ::mastodon_blender_view::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace mastodon_blender_view

