// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: protocol.proto
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_protocol_2eproto__INCLUDED
#define GRPC_protocol_2eproto__INCLUDED

#include "protocol.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace mastodon_blender_view {

class ViewService final {
 public:
  static constexpr char const* service_full_name() {
    return "mastodon_blender_view.ViewService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status addMovingSpot(::grpc::ClientContext* context, const ::mastodon_blender_view::AddMovingSpotRequest& request, ::mastodon_blender_view::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mastodon_blender_view::Empty>> AsyncaddMovingSpot(::grpc::ClientContext* context, const ::mastodon_blender_view::AddMovingSpotRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mastodon_blender_view::Empty>>(AsyncaddMovingSpotRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mastodon_blender_view::Empty>> PrepareAsyncaddMovingSpot(::grpc::ClientContext* context, const ::mastodon_blender_view::AddMovingSpotRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mastodon_blender_view::Empty>>(PrepareAsyncaddMovingSpotRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void addMovingSpot(::grpc::ClientContext* context, const ::mastodon_blender_view::AddMovingSpotRequest* request, ::mastodon_blender_view::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void addMovingSpot(::grpc::ClientContext* context, const ::mastodon_blender_view::AddMovingSpotRequest* request, ::mastodon_blender_view::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mastodon_blender_view::Empty>* AsyncaddMovingSpotRaw(::grpc::ClientContext* context, const ::mastodon_blender_view::AddMovingSpotRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mastodon_blender_view::Empty>* PrepareAsyncaddMovingSpotRaw(::grpc::ClientContext* context, const ::mastodon_blender_view::AddMovingSpotRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status addMovingSpot(::grpc::ClientContext* context, const ::mastodon_blender_view::AddMovingSpotRequest& request, ::mastodon_blender_view::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mastodon_blender_view::Empty>> AsyncaddMovingSpot(::grpc::ClientContext* context, const ::mastodon_blender_view::AddMovingSpotRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mastodon_blender_view::Empty>>(AsyncaddMovingSpotRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mastodon_blender_view::Empty>> PrepareAsyncaddMovingSpot(::grpc::ClientContext* context, const ::mastodon_blender_view::AddMovingSpotRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mastodon_blender_view::Empty>>(PrepareAsyncaddMovingSpotRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void addMovingSpot(::grpc::ClientContext* context, const ::mastodon_blender_view::AddMovingSpotRequest* request, ::mastodon_blender_view::Empty* response, std::function<void(::grpc::Status)>) override;
      void addMovingSpot(::grpc::ClientContext* context, const ::mastodon_blender_view::AddMovingSpotRequest* request, ::mastodon_blender_view::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::mastodon_blender_view::Empty>* AsyncaddMovingSpotRaw(::grpc::ClientContext* context, const ::mastodon_blender_view::AddMovingSpotRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mastodon_blender_view::Empty>* PrepareAsyncaddMovingSpotRaw(::grpc::ClientContext* context, const ::mastodon_blender_view::AddMovingSpotRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_addMovingSpot_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status addMovingSpot(::grpc::ServerContext* context, const ::mastodon_blender_view::AddMovingSpotRequest* request, ::mastodon_blender_view::Empty* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_addMovingSpot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_addMovingSpot() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_addMovingSpot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addMovingSpot(::grpc::ServerContext* /*context*/, const ::mastodon_blender_view::AddMovingSpotRequest* /*request*/, ::mastodon_blender_view::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestaddMovingSpot(::grpc::ServerContext* context, ::mastodon_blender_view::AddMovingSpotRequest* request, ::grpc::ServerAsyncResponseWriter< ::mastodon_blender_view::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_addMovingSpot<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_addMovingSpot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_addMovingSpot() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::mastodon_blender_view::AddMovingSpotRequest, ::mastodon_blender_view::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mastodon_blender_view::AddMovingSpotRequest* request, ::mastodon_blender_view::Empty* response) { return this->addMovingSpot(context, request, response); }));}
    void SetMessageAllocatorFor_addMovingSpot(
        ::grpc::MessageAllocator< ::mastodon_blender_view::AddMovingSpotRequest, ::mastodon_blender_view::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mastodon_blender_view::AddMovingSpotRequest, ::mastodon_blender_view::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_addMovingSpot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addMovingSpot(::grpc::ServerContext* /*context*/, const ::mastodon_blender_view::AddMovingSpotRequest* /*request*/, ::mastodon_blender_view::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* addMovingSpot(
      ::grpc::CallbackServerContext* /*context*/, const ::mastodon_blender_view::AddMovingSpotRequest* /*request*/, ::mastodon_blender_view::Empty* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_addMovingSpot<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_addMovingSpot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_addMovingSpot() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_addMovingSpot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addMovingSpot(::grpc::ServerContext* /*context*/, const ::mastodon_blender_view::AddMovingSpotRequest* /*request*/, ::mastodon_blender_view::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_addMovingSpot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_addMovingSpot() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_addMovingSpot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addMovingSpot(::grpc::ServerContext* /*context*/, const ::mastodon_blender_view::AddMovingSpotRequest* /*request*/, ::mastodon_blender_view::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestaddMovingSpot(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_addMovingSpot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_addMovingSpot() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->addMovingSpot(context, request, response); }));
    }
    ~WithRawCallbackMethod_addMovingSpot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addMovingSpot(::grpc::ServerContext* /*context*/, const ::mastodon_blender_view::AddMovingSpotRequest* /*request*/, ::mastodon_blender_view::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* addMovingSpot(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_addMovingSpot : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_addMovingSpot() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mastodon_blender_view::AddMovingSpotRequest, ::mastodon_blender_view::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mastodon_blender_view::AddMovingSpotRequest, ::mastodon_blender_view::Empty>* streamer) {
                       return this->StreamedaddMovingSpot(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_addMovingSpot() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status addMovingSpot(::grpc::ServerContext* /*context*/, const ::mastodon_blender_view::AddMovingSpotRequest* /*request*/, ::mastodon_blender_view::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedaddMovingSpot(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mastodon_blender_view::AddMovingSpotRequest,::mastodon_blender_view::Empty>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_addMovingSpot<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_addMovingSpot<Service > StreamedService;
};

}  // namespace mastodon_blender_view


#endif  // GRPC_protocol_2eproto__INCLUDED
